window.menuCategories = [
  { id: "all", name: "Tümü" },
  { id: "breakfast", name: "Kahvaltılar" },
  { id: "toast", name: "Tostlar" },
  { id: "sandwich", name: "Sandviçler" },
  { id: "food", name: "Yiyecekler" },
  { id: "dessert", name: "Tatlılar" },
  { id: "icecream", name: "Dondurma" },
  { id: "coffee", name: "Kahveler" },
  { id: "tea", name: "Çaylar" },
  { id: "cold-drinks", name: "Soğuk İçecekler" }
];

window.menuItems = [
  { id: "breakfast-1", categoryId: "breakfast", name: "Kahvaltı Tabağı", price: 450 },
  { id: "breakfast-2", categoryId: "breakfast", name: "Serpme Kahvaltı 2 Kişilik", price: 1200 },
  { id: "toast-1", categoryId: "toast", name: "Kaşarlı Tost", price: 280 },
  { id: "toast-2", categoryId: "toast", name: "Beyaz Peynirli, Domatesli, Kekikli Tost", price: 280 },
  { id: "toast-3", categoryId: "toast", name: "Karışık Tost", price: 300 },
  { id: "sandwich-1", categoryId: "sandwich", name: "Peynirli Sandviç", price: 280 },
  { id: "sandwich-2", categoryId: "sandwich", name: "Hindi Fümeli Sandviç", price: 300 },
  { id: "food-1", categoryId: "food", name: "Günün Çorbası", price: 185 },
  { id: "food-2", categoryId: "food", name: "Patates Kızartması", price: 200 },
  { id: "food-3", categoryId: "food", name: "Köfte", price: 550 },
  { id: "food-4", categoryId: "food", name: "Çocuk Köfte", price: 425 },
  { id: "food-5", categoryId: "food", name: "Hamburger", price: 475 },
  { id: "food-6", categoryId: "food", name: "Soğan Halkası", price: 225 },
  { id: "food-7", categoryId: "food", name: "Makarna (Tereyağlı)", price: 350 },
  { id: "food-8", categoryId: "food", name: "Makarna (Pestolu)", price: 400 },
  { id: "food-9", categoryId: "food", name: "Sıcak Sepet", price: 400 },
  { id: "food-10", categoryId: "food", name: "Omlet", price: 200 },
  { id: "food-11", categoryId: "food", name: "Kaşarlı Omlet", price: 250 },
  { id: "dessert-1", categoryId: "dessert", name: "Waffle", price: 450 },
  { id: "dessert-2", categoryId: "dessert", name: "Vişneli Mozaik Pasta", price: 330 },
  { id: "dessert-3", categoryId: "dessert", name: "Eliminasyon Keki", price: 350 },
  { id: "dessert-4", categoryId: "dessert", name: "Kurabiye (Porsiyon)", price: 180 },
  { id: "dessert-5", categoryId: "dessert", name: "Frambuazlı Cheesecake", price: 360 },
  { id: "dessert-6", categoryId: "dessert", name: "Yaban Mersinli Cheesecake", price: 360 },
  { id: "dessert-7", categoryId: "dessert", name: "Lotuslu Cheesecake", price: 360 },
  { id: "dessert-8", categoryId: "dessert", name: "Macaron", price: 50 },
  { id: "dessert-9", categoryId: "dessert", name: "Glutensiz Browni", price: 280 },
  { id: "dessert-10", categoryId: "dessert", name: "Sufle", price: 275 },
  { id: "icecream-1", categoryId: "icecream", name: "Çilekli (Top)", price: 75 },
  { id: "icecream-2", categoryId: "icecream", name: "Çikolatalı (Top)", price: 75 },
  { id: "coffee-1", categoryId: "coffee", name: "Americano", price: 160 },
  { id: "coffee-2", categoryId: "coffee", name: "Ice Americano", price: 170 },
  { id: "coffee-3", categoryId: "coffee", name: "Espresso", price: 100 },
  { id: "coffee-4", categoryId: "coffee", name: "Double Espresso", price: 130 },
  { id: "coffee-5", categoryId: "coffee", name: "Latte", price: 180 },
  { id: "coffee-6", categoryId: "coffee", name: "Ice Latte", price: 200 },
  { id: "coffee-7", categoryId: "coffee", name: "Flat White", price: 180 },
  { id: "coffee-8", categoryId: "coffee", name: "Ice Flat White", price: 200 },
  { id: "coffee-9", categoryId: "coffee", name: "Cappuccino", price: 180 },
  { id: "coffee-10", categoryId: "coffee", name: "Filtre Kahve", price: 160 },
  { id: "coffee-11", categoryId: "coffee", name: "Ice Filtre Kahve", price: 180 },
  { id: "coffee-12", categoryId: "coffee", name: "Sütlü Filtre Kahve", price: 180 },
  { id: "coffee-13", categoryId: "coffee", name: "Vanilyalı Filtre Kahve", price: 190 },
  { id: "coffee-14", categoryId: "coffee", name: "Türk Kahvesi", price: 120 },
  { id: "coffee-15", categoryId: "coffee", name: "Double Türk Kahvesi", price: 150 },
  { id: "coffee-16", categoryId: "coffee", name: "Dibek Kahvesi", price: 130 },
  { id: "coffee-17", categoryId: "coffee", name: "Sıcak Çikolata", price: 195 },
  { id: "tea-1", categoryId: "tea", name: "Çay", price: 60 },
  { id: "tea-2", categoryId: "tea", name: "Çay (Fincan)", price: 80 },
  { id: "tea-3", categoryId: "tea", name: "Bitki Çayı", price: 175 },
  { id: "tea-4", categoryId: "tea", name: "Yeşil Çay", price: 175 },
  { id: "cold-drinks-1", categoryId: "cold-drinks", name: "Limonata", price: 180 },
  { id: "cold-drinks-2", categoryId: "cold-drinks", name: "Portakal Suyu", price: 190 },
  { id: "cold-drinks-3", categoryId: "cold-drinks", name: "Milkshake (Günün Meyvesi)", price: 220 },
  { id: "cold-drinks-4", categoryId: "cold-drinks", name: "Su", price: 40 },
  { id: "cold-drinks-5", categoryId: "cold-drinks", name: "Sade Soda", price: 65 },
  { id: "cold-drinks-6", categoryId: "cold-drinks", name: "Meyveli Soda", price: 75 },
  { id: "cold-drinks-7", categoryId: "cold-drinks", name: "Churchill", price: 100 },
  { id: "cold-drinks-8", categoryId: "cold-drinks", name: "Cola", price: 95 },
  { id: "cold-drinks-9", categoryId: "cold-drinks", name: "Fanta", price: 95 },
  { id: "cold-drinks-10", categoryId: "cold-drinks", name: "Ice Tea", price: 90 },
  { id: "cold-drinks-11", categoryId: "cold-drinks", name: "Ayran", price: 50 },
  { id: "cold-drinks-12", categoryId: "cold-drinks", name: "Capri Sun", price: 75 }
];
